services:
  # Spring Boot Application
  app:
    build:
      context: ./minhm80
      dockerfile: Dockerfile
    container_name: minhm80-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/pos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge
